// icons/Icon_Helper.js
import {
  FaArrowUp, FaArrowRight, FaWhatsapp, FaEnvelope, FaPhone,
  FaBars, FaTimes, FaFacebook, FaInstagram, FaLinkedin,
  FaTwitter, FaYoutube, FaGithub, FaClock, FaCog,
  FaChartLine, FaIndustry, FaStar, FaGlobe, FaRocket,
  FaSatellite, FaMeteor, FaFire, FaShieldAlt, FaHeadset,
  FaFacebookF, FaPhoneAlt, FaMapMarkerAlt, FaHeart, FaCode,
  FaPaintBrush, FaLaptopCode,
  FaCodeBranch,
  FaServer,
  FaTools,
  FaLightbulb,
  FaMicrochip,
  FaBolt, FaDatabase,
  FaReact, FaNodeJs, FaPython, FaJava, FaAws, FaDocker,
  FaCrown, FaHandshake,
  FaTrophy,
  FaUserTie,
  FaPaperPlane,
  FaCheckCircle,
  FaMobile, FaPalette, FaCloud, FaRobot, FaShoppingCart,
  FaChevronRight, FaCogs,
  FaChevronLeft,
  FaAward
} from "react-icons/fa";
import { CiSettings } from "react-icons/ci";
import { SiMinutemailer } from "react-icons/si";
import { MdOutlineStarRate } from "react-icons/md";

const Icon_Helper = Object.freeze({
  FaArrowUp,
  FaArrowRight,
  FaWhatsapp,
  FaEnvelope,
  FaPhone,
  FaBars,
  FaTimes,
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaYoutube,
  FaGithub,
  FaClock,
  FaCog,
  FaChartLine,
  FaIndustry,
  FaStar,
  FaGlobe,
  FaRocket,
  FaSatellite,
  FaMeteor,
  FaFire,
  FaShieldAlt,
  FaHeadset,
  FaFacebookF,
  FaPhoneAlt,
  FaMapMarkerAlt,
  FaHeart,
  FaCode,
  FaPaintBrush,
  SiMinutemailer,
  FaLaptopCode,
  FaCodeBranch,
  FaServer,
  FaTools,
  FaLightbulb,
  FaMicrochip,
  FaBolt, FaDatabase,
  FaReact, FaNodeJs, FaPython, FaJava, FaAws, FaDocker,
  FaCrown, FaHandshake, FaTrophy,
  FaUserTie,
  FaPaperPlane,
  FaCheckCircle,
  FaMobile, FaPalette, FaCloud, FaRobot, FaShoppingCart,
  FaChevronRight, FaCogs,
  CiSettings, MdOutlineStarRate,
  FaChevronLeft, FaAward, 
});

export default Icon_Helper;